"""MCP-facing contracts and server factory."""

from invoice_triage.mcp_server.models import (
    AppliedRetrievalFilters,
    BudgetCheckStatus,
    BudgetEvaluation,
    BudgetSnapshot,
    CheckBudgetResponse,
    DuplicateCheckStatus,
    DuplicateFindingStatus,
    DuplicateInvoiceMatch,
    EvidenceDocument,
    EvidenceStatus,
    ExtractedInvoice,
    ExtractedInvoiceLine,
    ExtractInvoiceResponse,
    FlagDuplicateResponse,
    GroundingDocumentType,
    InvoiceIdentifierSummary,
    InvoiceExtractionStatus,
    InvoiceRecordSummary,
    LookupVendorResponse,
    ModelTokenUsage,
    RetrievalEvidence,
    RetrievalScores,
    RetrieveContextResponse,
    VendorLookupStatus,
    VendorMatch,
    VendorMatchType,
    VendorSummary,
)
from invoice_triage.mcp_server.extraction_tool import (
    InvoiceExtractionTool,
    InvoiceSourceReader,
)
from invoice_triage.mcp_server.retrieval_tool import RetrievalTool
from invoice_triage.mcp_server.structured_tools import StructuredDataTools

__all__ = [
    "AppliedRetrievalFilters",
    "BudgetCheckStatus",
    "BudgetEvaluation",
    "BudgetSnapshot",
    "CheckBudgetResponse",
    "DuplicateCheckStatus",
    "DuplicateFindingStatus",
    "DuplicateInvoiceMatch",
    "EvidenceDocument",
    "EvidenceStatus",
    "ExtractedInvoice",
    "ExtractedInvoiceLine",
    "ExtractInvoiceResponse",
    "FlagDuplicateResponse",
    "GroundingDocumentType",
    "InvoiceIdentifierSummary",
    "InvoiceExtractionStatus",
    "InvoiceExtractionTool",
    "InvoiceRecordSummary",
    "InvoiceSourceReader",
    "LookupVendorResponse",
    "ModelTokenUsage",
    "RetrievalEvidence",
    "RetrievalScores",
    "RetrievalTool",
    "RetrieveContextResponse",
    "StructuredDataTools",
    "VendorLookupStatus",
    "VendorMatch",
    "VendorMatchType",
    "VendorSummary",
]
